assign4part0: assign4part0.c nqueens_library.c
	gcc -Wall -Wextra assign4part0.c nqueens_library.c -o assign4part0

assign4part1: assign4part1.c nqueens_library.c
	gcc -Wall -Wextra assign4part1.c nqueens_library.c -o assign4part1

assign4part3: assign4part3.c nqueens_library.c
	gcc -Wall -Wextra assign4part3.c nqueens_library.c -o assign4part3

assign4part4: assign4part4.c nqueens_library.c
	gcc -Wall -Wextra assign4part4.c nqueens_library.c -o assign4part4 -pthread
 
assign4part5: assign4part5.c nqueens_library.c
	gcc -Wall -Wextra assign4part5.c nqueens_library.c -o assign4part5 -pthread

all: assign4part0 assign4part1 assign4part3 assign4part4 assign4part5
